### ISSUE TITLE
Feature request Dynamic load of csv, not just only from rootBundle.

### ISSUE THREAD

**Issue by singhtaranjeet** [erf/csv_localizations#1]
Can we supply another value in localizationDelegate for using pathProvider for getting the csv file.

As of now in the code i can see the usage of rootBundle or assetBundle for loading the file which is fine in case of pre defined assets, but we can also add option to use path provider in case someone want's to dynamically load the csv file.

If you are interested then i can also help in implementing this.

**Comment by erf** [comment]
What do you mean by using path provider to dynamically load the csv file? Can you explain a spesific use case? Path provider can only help with finding a local path right? If you want to fetch a network resource you can use a NetworkAssetBundle.

**Comment by singhtaranjeet** [comment]
my use case is downloading the csv file and saving it locally, and if file is not downloaded or may be user is offline then use the file that is in assets folder.

**Comment by erf** [comment]
This sounds like a special use case which you should either handle outside `csv_localizations` or by creating a custom `AssetBundle` class.

**Comment by singhtaranjeet** [comment]
I was trying to use AssetBundle but then realized it does not expose any api for updating existing assets, you are right may be custom AssetBundle is the solution.

**Comment by erf** [comment]
By extending `AssetBundle` i think you can handle your use case. You only need to use the `loadString` api and then check if it's in cache, or load it from the network or as a local asset.

**Comment by singhtaranjeet** [comment]
right, thanks for the direction mate. need to study the AssetBundle bit more. ;)

**Comment by erf** [comment]
No worries mate. Good luck :)
