### ISSUE TITLE
can u make return key instead of error if translation not exist?

### ISSUE THREAD

**Issue by aitinsan** [erf/csv_localizations#2]
that will help to write in flutter code already things prepeared for translations

**Comment by erf** [comment]
Can you be more specific what you would like and why?

If you'd like to return the key if a call to **string** does not exist, i'm not sure i'd like that. You should not call **string** with a key that does not exists.

**Comment by aitinsan** [comment]
I mean something like that
` String string(String key) {
    return _translationsMap[_langTag]?[key]??key;
  }`

**Comment by erf** [comment]
Why would you make a call to **string** with a key that doesn't exists?

**Comment by aitinsan** [comment]
I make it because I translate all things later. And for me, that's easier to write a translation that doesn't exist and then translate it. I think that will be normal.

**Comment by erf** [comment]
In my opinion you should have translations for all keys you try to invoke. If you don't have a translation for a key then something is wrong and an exception should be thrown.
