### ISSUE TITLE
can i change the separation from "," to ";"? 

### ISSUE THREAD

**Issue by Gustanabo** [erf/csv_localizations#3]
I've been struggling to make this work and just found out the problem was my excel saves .CSV files separating items with semicolons instead of commas. I know i can change excel settings to switch that, but can i do it in the package instead?

**Comment by erf** [comment]
It is not possible now, but the CSV package does support adding an optional delimiter. Would you like to try to make a PR for that? In that case we should accept all the arguments / configurations of the CSV package.

**Comment by erf** [comment]
I've now added support for all configurations supported by the `csv` package. You now need to add a configuration object with the arguments.
